language: node_js
node_js:
  - 10
  - 12
  - 14
os:
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_NODE_VERSION" == "8" || "$TRAVIS_NODE_VERSION" == "9" ]]; then npm remove midi-test --save-dev; fi
after_success: npm run coverage
